<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\MSBuild\Robust.Engine.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <OutputPath>../bin/MetadataGenerator</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

    <!-- Enable central package version management for this project -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

    <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" />
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>
</Project>

